# Generated by Django 4.0.1 on 2022-03-29 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkInByDateModel',
            fields=[
                ('checkInDate', models.DateField(editable=False, primary_key=True, serialize=False)),
                ('total_checkIn', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'checkInTotal',
                'verbose_name_plural': 'checkInTotals',
                'db_table': 'checkInbyDate',
                'ordering': ['checkInDate'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='customerPaymentAccount',
            fields=[
                ('transactionDate', models.DateField(editable=False)),
                ('studentId', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('customerName', models.CharField(editable=False, max_length=100)),
                ('paymenttype', models.CharField(editable=False, max_length=50)),
                ('Payment_Ref', models.CharField(editable=False, max_length=200)),
                ('credit', models.IntegerField(editable=False)),
                ('debit', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'CustomerAccountBalance',
                'verbose_name_plural': 'CustomerAccountBalances',
                'db_table': 'CustomerAccountBalance',
                'ordering': ['transactionDate'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='customerPerformance',
            fields=[
                ('studentId', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('customerName', models.CharField(editable=False, max_length=100)),
                ('countryList', models.CharField(editable=False, max_length=100)),
                ('sourceChannel', models.CharField(editable=False, max_length=100)),
                ('total_checkIn', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'customerPerformance',
                'verbose_name_plural': 'customerPerformances',
                'db_table': 'customerPerformance',
                'ordering': ['studentId'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='checkInData',
            fields=[
                ('checkInSeq', models.AutoField(primary_key=True, serialize=False)),
                ('studentId', models.IntegerField()),
                ('checkIn', models.IntegerField(default=1, editable=False)),
                ('checkInDate', models.DateField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='countryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryList', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='courseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursList', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='customerInfo',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=100, unique=True)),
                ('customerImg', models.ImageField(default='default.jpg', upload_to='media/student/imgs/')),
                ('adsRef', models.CharField(blank=True, max_length=200)),
                ('contactDate', models.DateField(default=datetime.datetime.now, editable=False)),
                ('leadeAge', models.IntegerField()),
                ('leadsLocation', models.CharField(max_length=100)),
                ('leadsContactNumber', models.IntegerField()),
                ('emailAddress', models.EmailField(max_length=254, unique=True)),
                ('leadsComment', models.CharField(max_length=1000)),
                ('leadsUrgent', models.BooleanField()),
                ('followUp', models.BooleanField(default=True)),
                ('Nationality', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='student.countrylist')),
                ('intersetList', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='student.courselist')),
            ],
        ),
        migrations.CreateModel(
            name='groupAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupAge', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='leadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceChannel', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='studioPackages',
            fields=[
                ('packageId', models.AutoField(primary_key=True, serialize=False)),
                ('PakageName', models.CharField(max_length=255, unique=True)),
                ('numberOfLessons', models.IntegerField()),
                ('packagePrice', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('courseName', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='student.courselist')),
                ('group_age', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='student.groupage')),
            ],
        ),
        migrations.CreateModel(
            name='customersPayments',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Ref', models.CharField(max_length=200)),
                ('transactionDate', models.DateField(default=datetime.datetime.now)),
                ('paymenttype', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], default='Cash', max_length=50)),
                ('paymentAmount', models.IntegerField()),
                ('currency', models.CharField(default='AED', max_length=20)),
                ('GB1', models.BooleanField(default=False)),
                ('StudentId', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='student.customerinfo')),
            ],
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='leadsChannel',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='student.leadsource'),
        ),
        migrations.CreateModel(
            name='customerFollowUp',
            fields=[
                ('commentSeq', models.AutoField(primary_key=True, serialize=False)),
                ('commentDate', models.DateField(default=datetime.datetime.now)),
                ('comments', models.CharField(max_length=200)),
                ('callBackOn', models.DateField()),
                ('gb1', models.BooleanField(default=False)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AssignPackage',
            fields=[
                ('soldPackageId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionDate', models.DateField(default=datetime.datetime.now)),
                ('startDate', models.DateField(default=datetime.datetime.now)),
                ('endDate', models.DateField(blank=True)),
                ('StudentId', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='student.customerinfo')),
                ('packageName', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='student.studiopackages')),
            ],
        ),
    ]
