# Generated by Django 4.0.1 on 2022-03-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='gbFlag',
            new_name='GB1',
        ),
    ]
