# Generated by Django 4.0.1 on 2022-04-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_customerfollowup_followupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupmodel',
            name='gb2',
            field=models.BooleanField(default=False),
        ),
    ]
