# Generated by Django 4.0.1 on 2022-03-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testtable',
        ),
    ]
