# Generated by Django 4.0.1 on 2022-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_followupmodel_gb2'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiopackages',
            name='freeTry',
            field=models.BooleanField(default=True),
        ),
    ]
