# Generated by Django 4.0.1 on 2022-03-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_payments_paymenttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
