# Generated by Django 4.0.1 on 2022-04-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studiopackages_freetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
