# Generated by Django 4.0.1 on 2022-06-06 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_followupmodel_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkInByUserModel',
            fields=[
                ('checkInSeq', models.AutoField(primary_key=True, serialize=False)),
                ('checkInValue', models.IntegerField(default=1)),
                ('checkInDate', models.DateField(default=datetime.datetime.now)),
                ('studentId', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.DO_NOTHING, to='student.customerinfo')),
            ],
        ),
    ]
