# Generated by Django 4.0.1 on 2022-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_customerspayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerPaymentAccount',
            fields=[
                ('transactionDate', models.DateField(editable=False)),
                ('studentId', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('customerName', models.CharField(editable=False, max_length=100)),
                ('paymenttype', models.CharField(editable=False, max_length=50)),
                ('Payment_Ref', models.CharField(editable=False, max_length=200)),
                ('credit', models.IntegerField(editable=False)),
                ('debit', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'CustomerAccountBalance',
                'verbose_name_plural': 'CustomerAccountBalances',
                'db_table': 'CustomerAccountBalance',
                'ordering': ['transactionDate'],
                'managed': False,
            },
        ),
    ]
